"""Stable machine-readable result codes; user-facing text lives in locales."""

from enum import Enum


class ProtocolErrorCode(str, Enum):
    INVALID_JSON = "invalid_json"
    INVALID_ENVELOPE = "invalid_envelope"
    MISSING_FIELD = "missing_field"
    INVALID_FIELD = "invalid_field"
    MESSAGE_TOO_LARGE = "message_too_large"
    UNSUPPORTED_PROTOCOL_VERSION = "unsupported_protocol_version"
    UNKNOWN_MESSAGE_TYPE = "unknown_message_type"
    DUPLICATE_REQUEST = "duplicate_request"
    UNAUTHORIZED = "unauthorized"
    FORBIDDEN = "forbidden"
    INVALID_TOKEN = "invalid_token"
    TOKEN_EXPIRED = "token_expired"
    STALE_CLIENT_STATE = "stale_client_state"
    SEQUENCE_GAP = "sequence_gap"
    PIECE_BUSY = "piece_busy"
    GAME_NOT_FOUND = "game_not_found"
    GAME_OVER = "game_over"
    GAME_PAUSED = "game_paused"
    ROOM_NOT_FOUND = "room_not_found"
    ROOM_FULL = "room_full"
    ROOM_CLOSED = "room_closed"
    INVALID_ROOM_CODE = "invalid_room_code"
    ALREADY_IN_GAME = "already_in_game"
    MATCHMAKING_TIMEOUT = "matchmaking_timeout"
    USERNAME_TAKEN = "username_taken"
    INVALID_CREDENTIALS = "invalid_credentials"
    INVALID_REGISTRATION = "invalid_registration"
    RECONNECT_EXPIRED = "reconnect_expired"
    INTERNAL_ERROR = "internal_error"
