"""Structural interfaces for collaborators used by the engine layer."""

from __future__ import annotations

from typing import Any, Protocol


class BoardPort(Protocol):
    @property
    def valid_colors(self) -> frozenset[str]: ...

    @property
    def num_rows(self) -> int: ...

    @property
    def num_cols(self) -> int: ...

    def get_cell(self, row: int, col: int) -> Any: ...

    def clear_cell(self, row: int, col: int) -> None: ...

    def detach_piece(self, row: int, col: int) -> Any: ...

    def place_piece(self, row: int, col: int, piece: Any) -> None: ...

    def restore_piece(
        self,
        row: int,
        col: int,
        piece: Any,
        promotion_piece_type: str | None = None,
    ) -> Any: ...


class RuleEnginePort(Protocol):
    @property
    def piece_rules(self) -> Any: ...

    def validate_move(
        self, board: BoardPort, from_row: int, from_col: int, to_row: int, to_col: int
    ) -> Any: ...


class ArbiterPort(Protocol):
    @property
    def elapsed_ms(self) -> int: ...

    @property
    def active_moves(self) -> list[dict]: ...

    def moving_origins(self) -> set[tuple[int, int]]: ...

    def has_active_motion(self) -> bool: ...

    def is_piece_resting(self, piece_id: int | None) -> bool: ...

    def rest_remaining_ms(self, piece_id: int | None) -> int | None: ...

    def start_rest(self, piece_id: int | None, remaining_ms: int) -> None: ...

    def clear_rest(self, piece_id: int | None) -> None: ...

    def remove_motion(self, motion: dict) -> None: ...

    def reservation_at(self, destination: tuple[int, int]) -> Any: ...

    def has_friendly_landing_reservation(
        self, destination: tuple[int, int], color: str
    ) -> bool: ...

    def reserve_landing(self, destination: tuple[int, int], piece: Any) -> bool: ...

    def release_landing(
        self, destination: tuple[int, int], piece_id: int | None = None
    ) -> None: ...


class ScorePolicy(Protocol):
    def points_for(self, captured_piece: Any) -> int: ...


class MovementPolicyPort(Protocol):
    def mode_for(self, piece: Any) -> Any: ...


class MotionOutcomePort(Protocol):
    def clear_source_cell(self, from_row: int, from_col: int) -> None: ...

    def execute_move(self, move: dict) -> None: ...

    def execute_move_to_cell(self, move: dict, to_row: int, to_col: int) -> None: ...

    def execute_move_to_airborne_origin(
        self, move: dict, to_row: int, to_col: int
    ) -> None: ...

    def complete_jump(self, move: dict) -> None: ...

    def complete_airborne_travel(self, move: dict) -> None: ...

    def cancel_motion(self, motion: dict, captured_at=None) -> None: ...


class EventSubscriber(Protocol):
    def handle(self, event: Any) -> None: ...


class EventPublisher(Protocol):
    def subscribe(self, event_type, subscriber: EventSubscriber) -> None: ...

    def unsubscribe(self, event_type, subscriber: EventSubscriber) -> None: ...

    def publish(self, event: Any) -> None: ...
